"use client"

import i18n from "i18next"
import { initReactI18next, useTranslation } from "react-i18next"
import LanguageDetector from "i18next-browser-languagedetector"
import { createContext, useContext, useState, useEffect, ReactNode } from "react"

// ─── Translation resources ────────────────────────────────────────────────────
// Keys missing from a language automatically fall back to English.

const en: Record<string, string> = {
  "nav.home": "Home",
  "nav.laptop": "Laptop Guide",
  "nav.learn": "Learn English",
  "nav.cv": "CV Builder",
  "home.title": "Welcome to Laois",
  "home.subtitle": "Your guide to life in Ireland",
  "home.info.title": "General Information",
  "home.info.text": "Welcome to Laois. This guide helps you understand daily life and services available to you.",
  "home.download.title": "Welcome Booklets",
  "home.download.text": "Download our comprehensive welcome guides with essential information for life in Laois.",
  "home.download.en": "Download English Booklet",
  "home.download.ar": "Download Arabic Booklet",
  "home.health.title": "Healthcare",
  "home.health.text": "Visit a GP for treatment. In emergencies call 112 or 999.",
  "home.learn.title": "Learn English",
  "home.learn.text": "Learning English is important for work and daily life.",
  "home.learn.btn": "Start Learning",
  "home.adapt.title": "How to Adapt",
  "home.adapt.1": "Meet your neighbors",
  "home.adapt.2": "Use local apps",
  "home.adapt.3": "Practice English daily",
  "home.adapt.4": "Respect the laws",
  "home.laptop.title": "Computer Use",
  "home.laptop.text": "Turning on the computer, using browser, and typing with keyboard.",
  "home.contact.title": "Contact Us",
  "home.contact.text": "Contact local support centers if you need help.",
  "laptop.title": "Laptop Guide",
  "laptop.intro": "These HP ProBook G7 laptops have been prepared for families in Mountmellick.",
  "laptop.login.title": "Login Details",
  "laptop.login.username": "Username",
  "laptop.login.password": "Password",
  "laptop.step1.title": "1. Turning On the Laptop",
  "laptop.step1.1": "Open the laptop screen.",
  "laptop.step1.2": "Press the power button (usually above the keyboard).",
  "laptop.step1.3": "Wait for the screen to turn on.",
  "laptop.step2.title": "2. Logging In",
  "laptop.step2.1": "Type the username: Admin",
  "laptop.step2.2": "Type the password: laptopuser",
  "laptop.step2.3": "Press Enter",
  "laptop.step3.title": "3. Connecting to WiFi",
  "laptop.step3.1": "Click the WiFi icon (bottom right corner).",
  "laptop.step3.2": "Select your home network.",
  "laptop.step3.3": "Enter your WiFi password.",
  "laptop.step3.4": "Click Connect.",
  "laptop.step4.title": "4. Using the Mouse (Touchpad)",
  "laptop.step4.1": "Slide one finger on the trackpad to move the arrow (cursor).",
  "laptop.step4.2": "Tap or click the left side to select items.",
  "laptop.step4.3": "Double-tap quickly to open folders or files.",
  "laptop.step5.title": "5. Learning the Keyboard",
  "laptop.step5.1": "Use the long Spacebar key at the bottom to make spaces between words.",
  "laptop.step5.2": "Press Backspace (top right arrow) to erase any mistakes.",
  "laptop.step5.3": "Hold down the Shift key while typing a letter to make it a CAPITAL letter.",
  "laptop.step6.title": "6. Opening the Internet (Chrome in Arabic)",
  "laptop.step6.1": "Find and double-click the Google Chrome icon on the screen.",
  "laptop.step6.2": "The Portlaoise Council has set Arabic as the default main language for your browser.",
  "laptop.step6.3": "Websites and settings will automatically offer to translate or show in Arabic to help you browse easily.",
  "laptop.step7.title": "7. Staying Safe Online",
  "laptop.step7.1": "Only visit websites you know and trust.",
  "laptop.step7.2": "Never click on strange pop-up messages or boxes that claim you won prizes.",
  "laptop.step7.3": "Do not type personal password details unless you are sure of the website.",
  "laptop.step8.title": "8. Adjusting Volume and Brightness",
  "laptop.step8.1": "Look at the very top row of your keyboard for volume icons (speakers).",
  "laptop.step8.2": "Press the buttons with the small speaker pictures to turn sound up, down, or mute it.",
  "laptop.step8.3": "You can change screen brightness using the small sun icons on the keyboard row.",
  "laptop.step9.title": "9. Charging & Physical Care",
  "laptop.step9.1": "Plug in the charger to the side of the laptop when the battery icon looks low.",
  "laptop.step9.2": "Keep food and drinks away from the keyboard to avoid accidents.",
  "laptop.step9.3": "Always place the laptop on a hard, flat surface (like a table) so it does not overheat.",
  "laptop.step10.title": "10. Turning Off Safely (Shut Down)",
  "laptop.step10.1": "Click the Start menu button (the Windows icon in the bottom left corner).",
  "laptop.step10.2": "Click the Power icon, then choose 'Shut Down'.",
  "laptop.step10.3": "Wait until the lights go completely black before closing the laptop screen.",
  "learn.title": "English Learning Resources",
  "learn.subtitle": "Online resources to help you learn English from home",
  "learn.resources": "Resources",
  "learn.platform": "Learning Platform",
  "learn.intro": "There is a great Padlet resource with multiple useful links.",
  "learn.padlet": "Open Padlet Resources",
  "learn.downloads": "Download ESOL Documents",
  "learn.en.doc": "Download English Document",
  "learn.ar.doc": "Download Arabic Document",
  "learn.platform.title": "Transparent Language Online",
  "learn.platform.text": "Access interactive language learning platform:",
  "learn.platform.btn": "Open Platform",
  "learn.websites": "Websites",
  "learn.apps": "Apps",
  "learn.podcasts": "Podcasts",
  "learn.youtube": "YouTube",
  "learn.british.council": "British Council - Learn English Online",
  "learn.british.council.desc": "A brilliant website for all levels with listening, reading, writing, and speaking resources.",
  "learn.bbc": "BBC Learning English",
  "learn.bbc.desc": "The BBC's Learning English websites have lots of resources for all levels.",
  "learn.breaking.news": "Breaking News English",
  "learn.breaking.news.desc": "Free site with ready-to-use ESL lessons and graded news articles.",
  "learn.duolingo": "Duolingo",
  "learn.duolingo.desc": "A very well-known app with many languages to choose from.",
  "learn.memrise": "Memrise",
  "learn.memrise.desc": "Another good app with many languages to choose from.",
  "learn.grammar.app": "Learn English Grammar",
  "learn.grammar.app.desc": "British Council app for practicing grammar at all levels.",
  "learn.6min": "6-Minute English",
  "learn.6min.desc": "BBC podcast for B1/B2 learners.",
  "learn.vocabulary": "Learning English Vocabulary",
  "learn.vocabulary.desc": "BBC podcast for A2+ learners.",
  "learn.business": "Business English Podcast",
  "learn.business.desc": "English language for business situations.",
  "learn.scenarios": "Conversation Scenarios",
  "learn.scenarios.desc": "Practise real conversations for everyday life in Portlaoise — booking a GP, enrolling at school, using the bus, and more.",
  "learn.scenarios.browse": "Browse Conversation Scenarios",

  "scenarios.title": "Conversation Scenarios",
  "scenarios.subtitle": "Real-life conversations to help you feel confident in everyday situations in Portlaoise, Ireland. Tap a scenario to read and practise.",
  "scenarios.back": "Back",
  "scenarios.tips": "Useful Tips for this Situation",
  "scenarios.level": "Level",

  "scenarios.gp.title": "Booking a GP Appointment",
  "scenarios.gp.description": "Learn how to phone your local doctor's surgery to make or change an appointment.",
  "scenarios.gp.line1.speaker": "Receptionist",
  "scenarios.gp.line1.text": "Good morning, Portlaoise Medical Centre. How can I help you?",
  "scenarios.gp.line2.speaker": "You",
  "scenarios.gp.line2.text": "Hello. I would like to make an appointment with a doctor, please.",
  "scenarios.gp.line3.speaker": "Receptionist",
  "scenarios.gp.line3.text": "Of course. Is it urgent, or is it a routine visit?",
  "scenarios.gp.line4.speaker": "You",
  "scenarios.gp.line4.text": "It is a routine visit. I have had a sore throat for three days.",
  "scenarios.gp.line5.speaker": "Receptionist",
  "scenarios.gp.line5.text": "I see. Can I take your name and date of birth?",
  "scenarios.gp.line6.speaker": "You",
  "scenarios.gp.line6.text": "My name is Fatima Hassan. My date of birth is the 5th of March 1990.",
  "scenarios.gp.line7.speaker": "Receptionist",
  "scenarios.gp.line7.text": "Thank you. We have an appointment available on Thursday at 10:30 in the morning. Does that work for you?",
  "scenarios.gp.line8.speaker": "You",
  "scenarios.gp.line8.text": "Yes, Thursday at 10:30 is perfect. Thank you very much.",
  "scenarios.gp.line9.speaker": "Receptionist",
  "scenarios.gp.line9.text": "You're welcome. Please bring your medical card if you have one. See you Thursday. Goodbye.",
  "scenarios.gp.line10.speaker": "You",
  "scenarios.gp.line10.text": "Thank you. Goodbye.",
  "scenarios.gp.tip1": "Say 'I would like to make an appointment' — it is polite and clear.",
  "scenarios.gp.tip2": "Give your name clearly, spelling it if needed: 'F — A — T — I — M — A'.",
  "scenarios.gp.tip3": "Ask 'Could you repeat that, please?' if you do not understand.",
  "scenarios.gp.tip4": "Bring your medical card (if you have one) and PPS number.",
  "scenarios.gp.tip5": "If it is very urgent, say: 'I need to see a doctor today — it is quite urgent.'",

  "scenarios.school.title": "Enrolling a Child at School",
  "scenarios.school.description": "How to contact a school in Portlaoise to ask about enrolling your child.",
  "scenarios.school.line1.speaker": "School Secretary",
  "scenarios.school.line1.text": "Good afternoon, Scoil Mhuire Primary School. How can I help?",
  "scenarios.school.line2.speaker": "You",
  "scenarios.school.line2.text": "Hello. I am calling about enrolling my daughter. She is seven years old.",
  "scenarios.school.line3.speaker": "School Secretary",
  "scenarios.school.line3.text": "Thank you for calling. We do have places available. Can I ask what class she would be joining — that would be First Class for a seven-year-old.",
  "scenarios.school.line4.speaker": "You",
  "scenarios.school.line4.text": "Yes, First Class. We have just moved to Portlaoise from abroad.",
  "scenarios.school.line5.speaker": "School Secretary",
  "scenarios.school.line5.text": "Welcome to Portlaoise! You will need to fill in an enrolment form. You can collect it from the school office or I can email it to you.",
  "scenarios.school.line6.speaker": "You",
  "scenarios.school.line6.text": "Could you email it, please? My email is fatima.hassan@email.com.",
  "scenarios.school.line7.speaker": "School Secretary",
  "scenarios.school.line7.text": "Perfect. You will also need a copy of her birth certificate and her PPS number. Do you have those?",
  "scenarios.school.line8.speaker": "You",
  "scenarios.school.line8.text": "I have her birth certificate. I am still waiting for the PPS number.",
  "scenarios.school.line9.speaker": "School Secretary",
  "scenarios.school.line9.text": "That is fine — you can bring it later. Once we have the form, we will be in touch to arrange a start date.",
  "scenarios.school.line10.speaker": "You",
  "scenarios.school.line10.text": "Thank you so much. That is very helpful.",
  "scenarios.school.tip1": "Bring: birth certificate, PPS number (when available), vaccination record (immunisation book).",
  "scenarios.school.tip2": "Say: 'We have just arrived from...' — schools understand and are very welcoming.",
  "scenarios.school.tip3": "Ask: 'Does the school have English language support (EAL)?' — many schools do.",
  "scenarios.school.tip4": "Portlaoise has several primary schools — you can apply to more than one.",
  "scenarios.school.tip5": "The school year runs September to June.",

  "scenarios.council.title": "Contacting Laois County Council",
  "scenarios.council.description": "Reporting a maintenance issue with a council property (roof and walls).",
  "scenarios.council.line1.speaker": "Council Staff",
  "scenarios.council.line1.text": "Good morning, Laois County Council. How can I help you today?",
  "scenarios.council.line2.speaker": "You",
  "scenarios.council.line2.text": "Hello. I am a council tenant and I need to report a problem with my house. There is a leak in the roof and damp on the walls.",
  "scenarios.council.line3.speaker": "Council Staff",
  "scenarios.council.line3.text": "I am sorry to hear that. As a council property, we are responsible for structural repairs. Can I take your address, please?",
  "scenarios.council.line4.speaker": "You",
  "scenarios.council.line4.text": "Yes. It is 14 Oak Drive, Portlaoise.",
  "scenarios.council.line5.speaker": "Council Staff",
  "scenarios.council.line5.text": "Thank you. I will log this with our housing maintenance team. An inspector will contact you to look at the roof and walls.",
  "scenarios.council.line6.speaker": "You",
  "scenarios.council.line6.text": "Thank you. Is there anything I should do in the meantime to stop the damp from getting worse?",
  "scenarios.council.line7.speaker": "Council Staff",
  "scenarios.council.line7.text": "Please keep the rooms well-ventilated if possible and wipe down any surface moisture. We will try to get someone out to you quickly.",
  "scenarios.council.line8.speaker": "You",
  "scenarios.council.line8.text": "Thank you very much for your help. I look forward to hearing from the inspector.",
  "scenarios.council.tip1": "Laois County Council number: 057 866 4000.",
  "scenarios.council.tip2": "For housing repairs, say: 'I am a council tenant and I want to report a maintenance issue.'",
  "scenarios.council.tip3": "The council is responsible for the exterior structure, including the roof, walls, and main drains.",
  "scenarios.council.tip4": "You can also visit the Council offices on James Fintan Lalor Avenue, Portlaoise.",
  "scenarios.council.tip5": "Say: 'Could I speak to the housing maintenance department, please?' if transferred.",

  "scenarios.pharmacy.title": "At the Pharmacy",
  "scenarios.pharmacy.description": "Collecting a prescription or asking for advice about medicine.",
  "scenarios.pharmacy.line1.speaker": "Pharmacist",
  "scenarios.pharmacy.line1.text": "Hello, how can I help you?",
  "scenarios.pharmacy.line2.speaker": "You",
  "scenarios.pharmacy.line2.text": "Hello. I have a prescription from my doctor. I would like to collect it, please.",
  "scenarios.pharmacy.line3.speaker": "Pharmacist",
  "scenarios.pharmacy.line3.text": "Of course. Can I have your name and date of birth?",
  "scenarios.pharmacy.line4.speaker": "You",
  "scenarios.pharmacy.line4.text": "My name is Ahmed Al-Rawi. Date of birth is 12th of July 1985.",
  "scenarios.pharmacy.line5.speaker": "Pharmacist",
  "scenarios.pharmacy.line5.text": "Thank you. Do you have a medical card or GP visit card?",
  "scenarios.pharmacy.line6.speaker": "You",
  "scenarios.pharmacy.line6.text": "Yes, I have a medical card.",
  "scenarios.pharmacy.line7.speaker": "Pharmacist",
  "scenarios.pharmacy.line7.text": "Perfect. This prescription is for antibiotics. Take one tablet three times a day with food. Finish the full course even if you feel better. Any questions?",
  "scenarios.pharmacy.line8.speaker": "You",
  "scenarios.pharmacy.line8.text": "Can I take these with other medicines?",
  "scenarios.pharmacy.line9.speaker": "Pharmacist",
  "scenarios.pharmacy.line9.text": "What other medicines are you taking?",
  "scenarios.pharmacy.line10.speaker": "You",
  "scenarios.pharmacy.line10.text": "I am taking tablets for blood pressure — Amlodipine 5mg.",
  "scenarios.pharmacy.line11.speaker": "Pharmacist",
  "scenarios.pharmacy.line11.text": "That is fine, no interaction. But avoid alcohol while on the antibiotics.",
  "scenarios.pharmacy.line12.speaker": "You",
  "scenarios.pharmacy.line12.text": "Understood. Thank you very much.",
  "scenarios.pharmacy.tip1": "Bring your prescription, medical card, and photo ID.",
  "scenarios.pharmacy.tip2": "Say: 'I do not understand — could you explain that more slowly, please?'",
  "scenarios.pharmacy.tip3": "Ask: 'Are there any side effects I should know about?'",
  "scenarios.pharmacy.tip4": "Pharmacists give free advice — you do not always need a doctor for minor problems.",
  "scenarios.pharmacy.tip5": "Many pharmacies in Portlaoise offer free blood pressure checks.",

  "scenarios.bus.title": "Using the Bus / Public Transport",
  "scenarios.bus.description": "Buying a ticket and asking about bus routes in Portlaoise.",
  "scenarios.bus.line1.speaker": "You",
  "scenarios.bus.line1.text": "Excuse me, does this bus go to Dublin?",
  "scenarios.bus.line2.speaker": "Driver",
  "scenarios.bus.line2.text": "Yes, this is the Dublin Busáras service. Are you getting on?",
  "scenarios.bus.line3.speaker": "You",
  "scenarios.bus.line3.text": "Yes, please. How much is a single ticket to Dublin?",
  "scenarios.bus.line4.speaker": "Driver",
  "scenarios.bus.line4.text": "That is €13.50 for a single. Do you have the Leap card?",
  "scenarios.bus.line5.speaker": "You",
  "scenarios.bus.line5.text": "No, I do not have a Leap card. I will pay by cash.",
  "scenarios.bus.line6.speaker": "Driver",
  "scenarios.bus.line6.text": "No problem. €13.50 please. I can give change.",
  "scenarios.bus.line7.speaker": "You",
  "scenarios.bus.line7.text": "Here is €20. Thank you. What time do we arrive in Dublin?",
  "scenarios.bus.line8.speaker": "Driver",
  "scenarios.bus.line8.text": "About 1 hour 15 minutes. We arrive around 11:45.",
  "scenarios.bus.line9.speaker": "You",
  "scenarios.bus.line9.text": "Thank you. Is there a toilet on the bus?",
  "scenarios.bus.line10.speaker": "Driver",
  "scenarios.bus.line10.text": "No, there is no toilet. There is a stop in Monasterevin in about 20 minutes if needed.",
  "scenarios.bus.line11.speaker": "You",
  "scenarios.bus.line11.text": "Thank you very much.",
  "scenarios.bus.tip1": "The Leap Card saves money on buses and trains. Get one at the train station or many shops.",
  "scenarios.bus.tip2": "Bus Éireann runs from Portlaoise to Dublin, Cork, and other cities.",
  "scenarios.bus.tip3": "The train (Irish Rail) is another option — Portlaoise train station is central.",
  "scenarios.bus.tip4": "Say: 'Which bus stop do I need for...?' if you are unsure where to get off.",
  "scenarios.bus.tip5": "Check timetables at buseireann.ie or irishrail.ie.",

  "scenarios.welfare.title": "Visiting the Social Welfare / Intreo Office",
  "scenarios.welfare.description": "Asking about benefits, jobseeker's allowance, or registering for support.",
  "scenarios.welfare.line1.speaker": "Intreo Staff",
  "scenarios.welfare.line1.text": "Good morning. How can I help you today?",
  "scenarios.welfare.line2.speaker": "You",
  "scenarios.welfare.line2.text": "Good morning. I am looking for information about Jobseeker's Allowance. I recently lost my job.",
  "scenarios.welfare.line3.speaker": "Intreo Staff",
  "scenarios.welfare.line3.text": "I am sorry to hear that. How long have you been living in Ireland?",
  "scenarios.welfare.line4.speaker": "You",
  "scenarios.welfare.line4.text": "I have been living here for two years. I have a residence permit.",
  "scenarios.welfare.line5.speaker": "Intreo Staff",
  "scenarios.welfare.line5.text": "Good. You will need to show your PPSN, proof of address, and your residence permit. Have you registered with us before?",
  "scenarios.welfare.line6.speaker": "You",
  "scenarios.welfare.line6.text": "No, this is my first time. I am not sure what I need to do.",
  "scenarios.welfare.line7.speaker": "Intreo Staff",
  "scenarios.welfare.line7.text": "No problem. I will give you a form to fill in. We can go through it together if you like.",
  "scenarios.welfare.line8.speaker": "You",
  "scenarios.welfare.line8.text": "Yes please. My English is not perfect and I want to make sure I fill it in correctly.",
  "scenarios.welfare.line9.speaker": "Intreo Staff",
  "scenarios.welfare.line9.text": "Of course — take your time. If you get confused by any of the questions, just stop and ask me to explain them.",
  "scenarios.welfare.line10.speaker": "You",
  "scenarios.welfare.line10.text": "Thank you. If I do not understand a word, I will ask you. I appreciate your help.",
  "scenarios.welfare.tip1": "Intreo Portlaoise is located at Portlaoise Employment Services, Togher Industrial Estate.",
  "scenarios.welfare.tip2": "Bring: PPSN card, photo ID, proof of address (e.g. a utility bill or letter), and residence permit.",
  "scenarios.welfare.tip3": "Do not hesitate to ask questions if you are confused by any part of the application forms.",
  "scenarios.welfare.tip4": "Say: 'I would like to speak to a case officer, please.'",
  "scenarios.welfare.tip5": "You can also apply online at mywelfare.ie.",
  
  "camps.subtitle": "Find the best camps for children and young people",
  "camps.filter.all": "All Types",
  "camps.filter.sport": "Sport",
  "camps.filter.outdoor": "Outdoor",
  "camps.filter.creative": "Creative",
  "camps.location": "Location",
  "camps.map": "View Map",
  "theme.light": "Light",
  "theme.dark": "Dark",
  "lang.switch": "العربية",
}

const ar: Record<string, string> = {
  "nav.home": "الرئيسية",
  "nav.laptop": "دليل الحاسوب",
  "nav.learn": "تعلم الإنجليزية",
  "nav.camps": "مخيمات الصيف",
  "nav.cv": "بناء السيرة الذاتية",
  "home.title": "مرحباً بكم في لاويس",
  "home.subtitle": "دليلكم للحياة في أيرلندا",
  "home.info.title": "معلومات عامة",
  "home.info.text": "مرحباً بكم في لاويس. هذا الدليل يساعدكم على فهم الحياة اليومية والخدمات المتوفرة.",
  "home.download.title": "كتيبات الترحيب",
  "home.download.text": "حمّل أدلة الترحيب الشاملة مع المعلومات الأساسية للحياة في لاويس.",
  "home.download.en": "تحميل الكتيب الإنجليزي",
  "home.download.ar": "تحميل الكتيب العربي",
  "home.health.title": "الرعاية الصحية",
  "home.health.text": "زوروا الطبيب العام للعلاج. في الحالات الطارئة اتصلوا بـ 112 أو 999.",
  "home.learn.title": "تعلم الإنجليزية",
  "home.learn.text": "تعلم اللغة الإنجليزية مهم للعمل والحياة اليومية.",
  "home.learn.btn": "ابدأ التعلم",
  "home.adapt.title": "كيف تتأقلم",
  "home.adapt.1": "تعرف على جيرانك",
  "home.adapt.2": "استخدم التطبيقات المحلية",
  "home.adapt.3": "تدرب على الإنجليزية يومياً",
  "home.adapt.4": "احترم القوانين",
  "home.laptop.title": "استخدام الحاسوب",
  "home.laptop.text": "تشغيل الحاسوب، استخدام المتصفح، والكتابة باستخدام لوحة المفاتيح.",
  "home.contact.title": "اتصل بنا",
  "home.contact.text": "تواصل مع مراكز الدعم المحلي عند الحاجة.",
  "laptop.title": "دليل استخدام اللابتوب",
  "laptop.intro": "تم إعداد أجهزة HP ProBook G7 لاستخدام العائلات في ماونتمليك.",
  "laptop.login.title": "تفاصيل تسجيل الدخول",
  "laptop.login.username": "اسم المستخدم",
  "laptop.login.password": "كلمة المرور",
  "laptop.step1.title": "1. تشغيل الجهاز",
  "laptop.step1.1": "افتح شاشة اللابتوب.",
  "laptop.step1.2": "اضغط على زر التشغيل (عادةً ما يكون فوق لوحة المفاتيح).",
  "laptop.step1.3": "انتظر حتى تفتح الشاشة بالكامل.",
  "laptop.step2.title": "2. تسجيل الدخول",
  "laptop.step2.1": "اكتب اسم المستخدم: Admin",
  "laptop.step2.2": "اكتب كلمة المرور: laptopuser",
  "laptop.step2.3": "اضغط على زر الإدخال (Enter)",
  "laptop.step3.title": "3. الاتصال بالإنترنت (WiFi)",
  "laptop.step3.1": "اضغط على رمز الواي فاي (في الزاوية السفلية اليمنى).",
  "laptop.step3.2": "اختر شبكة الإنترنت المنزلية الخاصة بك.",
  "laptop.step3.3": "أدخل كلمة مرور شبكة الواي فاي الخاصة بك.",
  "laptop.step3.4": "اضغط على اتصال (Connect).",
  "laptop.step4.title": "4. استخدام الفأرة (لوحة اللمس)",
  "laptop.step4.1": "حرك إصبعاً واحداً على لوحة اللمس لتحريك السهم (المؤشر) على الشاشة.",
  "laptop.step4.2": "انقر على الجانب الأيسر للوحة اللمس لاختيار أو فتح الأشياء.",
  "laptop.step4.3": "انقر مرتين سريعتين لفتح المجلدات أو الملفات والمواقع.",
  "laptop.step5.title": "5. مهارات استخدام لوحة المفاتيح",
  "laptop.step5.1": "استخدم زر المسافة الطويل (Spacebar) في الأسفل لترك فراغ بين الكلمات.",
  "laptop.step5.2": "اضغط على زر مسح التراجع (Backspace) في الأعلى لإصلاح أي أخطاء إملائية.",
  "laptop.step5.3": "اضغط مطولاً على زر (Shift) أثناء كتابة حرف لجعله حرفاً كبيراً (CAPITAL).",
  "laptop.step6.title": "6. فتح الإنترنت (متصفح كروم باللغة العربية)",
  "laptop.step6.1": "ابحث عن أيقونة متصفح Google Chrome على الشاشة واضغط عليها مرتين.",
  "laptop.step6.2": "قام مجلس بلدية بورتلاو بإعداد اللغة العربية كلغة أساسية لمتصفحك.",
  "laptop.step6.3": "ستقوم المواقع والإعدادات بعرض المحتوى أو ترجمته للغة العربية تلقائياً لتسهيل التصفح لك.",
  "laptop.step7.title": "7. الأمان والسلامة على الإنترنت",
  "laptop.step7.1": "قم بزيارة المواقع الإلكترونية التي تعرفها وتثق بها فقط.",
  "laptop.step7.2": "تجنب الضغط على الإعلانات المنبثقة الغريبة أو النوافذ التي تدعي فوزك بجوائز.",
  "laptop.step7.3": "لا تقم بكتابة كلمات المرور الخاصة بك إلا إذا كنت متأكداً تماماً من صحة الموقع.",
  "laptop.step8.title": "8. تعديل الصوت وسطوع الشاشة",
  "laptop.step8.1": "ابحث في الصف العلوي من لوحة المفاتيح عن أزرار التحكم بالصوت (رموز مكبرات الصوت).",
  "laptop.step8.2": "اضغط على الأزرار لرفع الصوت، خفضه، أو كتمه تماماً.",
  "laptop.step8.3": "يمكنك أيضاً تعديل درجة إضاءة الشاشة باستخدام أزرار الرموز التي تشبه الشمس الصغيرة.",
  "laptop.step9.title": "9. شحن الجهاز والعناية به",
  "laptop.step9.1": "قم بتوصيل الشاحن بجانب اللابتوب عندما تلاحظ انخفاض مؤشر البطارية.",
  "laptop.step9.2": "حافظ على الأطعمة والمشروبات بعيداً عن لوحة المفاتيح لتجنب أي حوادث أو أعطال.",
  "laptop.step9.3": "ضع الجهاز دائماً على سطح صلب ومستوٍ (مثل الطاولة) لضمان عدم ارتفاع حرارته.",
  "laptop.step10.title": "10. إيقاف التشغيل بأمان (Shut Down)",
  "laptop.step10.1": "اضغط على قائمة ابدأ (شعار Windows في الزاوية السفلية).",
  "laptop.step10.2": "اضغط على رمز الطاقة (Power)، ثم اختر 'إيقاف التشغيل' (Shut Down).",
  "laptop.step10.3": "انتظر حتى تنطفئ شاشات وأضواء الجهاز تماماً قبل إغلاق غطاء اللابتوب.",
  "learn.title": "موارد تعلم اللغة الإنجليزية",
  "learn.subtitle": "موارد عبر الإنترنت لمساعدتك على تعلم الإنجليزية من المنزل",
  "learn.resources": "الموارد",
  "learn.platform": "منصة التعلم",
  "learn.intro": "هناك مورد رائع يحتوي على روابط مفيدة.",
  "learn.padlet": "افتح موارد Padlet",
  "learn.downloads": "تحميل ملفات ESOL",
  "learn.en.doc": "تحميل الملف الإنجليزي",
  "learn.ar.doc": "تحميل الملف العربي",
  "learn.platform.title": "منصة تعلم اللغة",
  "learn.platform.text": "استخدم المنصة التفاعلية لتعلم اللغة:",
  "learn.platform.btn": "افتح المنصة",
  "learn.websites": "مواقع إلكترونية",
  "learn.apps": "تطبيقات",
  "learn.podcasts": "بودكاست",
  "learn.youtube": "يوتيوب",
  "learn.british.council": "المجلس الثقافي البريطاني - تعلم الإنجليزية",
  "learn.british.council.desc": "موقع رائع لجميع المستويات مع موارد الاستماع والقراءة والكتابة والتحدث.",
  "learn.bbc": "BBC تعلم الإنجليزية",
  "learn.bbc.desc": "مواقع BBC لتعلم الإنجليزية تحتوي على الكثير من الموارد لجميع المستويات.",
  "learn.breaking.news": "Breaking News English",
  "learn.breaking.news.desc": "موقع مجاني مع دروس جاهزة ومقالات إخبارية متدرجة.",
  "learn.duolingo": "دوولينجو",
  "learn.duolingo.desc": "تطبيق مشهور جداً مع العديد من اللغات للاختيار من بينها.",
  "learn.memrise": "Memrise",
  "learn.memrise.desc": "تطبيق جيد آخر مع العديد من اللغات للاختيار من بينها.",
  "learn.grammar.app": "تعلم قواعد الإنجليزية",
  "learn.grammar.app.desc": "تطبيق المجلس الثقافي البريطاني لممارسة القواعد في جميع المستويات.",
  "learn.6min": "الإنجليزية في 6 دقائق",
  "learn.6min.desc": "بودكاست BBC للمتعلمين B1/B2.",
  "learn.vocabulary": "تعلم المفردات الإنجليزية",
  "learn.vocabulary.desc": "بودكاست BBC للمتعلمين A2+.",
  "learn.business": "بودكاست الإنجليزية للأعمال",
  "learn.business.desc": "اللغة الإنجليزية لمواقف العمل.",
  "learn.scenarios": "سيناريوهات المحادثة",
  "learn.scenarios.desc": "تدرب على محادثات حقيقية للحياة اليومية في بورتلاويس — حجز موعد مع الطبيب، المدرسة، وأكثر.",
  "learn.scenarios.browse": "استعرض سيناريوهات المحادثة",
  
  "scenarios.title": "سيناريوهات المحادثة",
  "scenarios.subtitle": "محادثات حقيقية لمساعدتك على الشعور بالثقة في المواقف اليومية في بورتلاويس، أيرلندا. اضغط على سيناريو لقراءته والتدرب عليه.",
  "scenarios.back": "رجوع",
  "scenarios.tips": "نصائح مفيدة لهذا الموقف",
  "scenarios.level": "المستوى",

  "scenarios.gp.title": "حجز موعد مع الطبيب العام (GP)",
  "scenarios.gp.description": "تعلم كيفية الاتصال بمركز الطب المحلي لحجز موعد أو تغييره.",
  "scenarios.gp.line1.speaker": "موظف الاستقبال",
  "scenarios.gp.line1.text": "صباح الخير، مركز بورتلاويس الطبي. كيف يمكنني مساعدتك؟",
  "scenarios.gp.line2.speaker": "أنت",
  "scenarios.gp.line2.text": "مرحباً. أود حجز موعد مع الطبيب، من فضلك.",
  "scenarios.gp.line3.speaker": "موظف الاستقبال",
  "scenarios.gp.line3.text": "بالتأكيد. هل الأمر عاجل أم أنها زيارة روتينية؟",
  "scenarios.gp.line4.speaker": "أنت",
  "scenarios.gp.line4.text": "إنها زيارة روتينية. يعاني حلقي من ألم منذ ثلاثة أيام.",
  "scenarios.gp.line5.speaker": "موظف الاستقبال",
  "scenarios.gp.line5.text": "أفهم ذلك. هل يمكنني معرفة اسمك وتاريخ ميلادك؟",
  "scenarios.gp.line6.speaker": "أنت",
  "scenarios.gp.line6.text": "اسمي فاطمة حسن. تاريخ ميلادي هو 5 مارس 1990.",
  "scenarios.gp.line7.speaker": "موظف الاستقبال",
  "scenarios.gp.line7.text": "شكراً لكِ. لدينا موعد متاح يوم الخميس الساعة 10:30 صباحاً. هل يناسبك هذا الوقت؟",
  "scenarios.gp.line8.speaker": "أنت",
  "scenarios.gp.line8.text": "نعم، يوم الخميس الساعة 10:30 ممتاز جداً. شكراً جزيلاً لك.",
  "scenarios.gp.line9.speaker": "موظف الاستقبال",
  "scenarios.gp.line9.text": "على الرحب والسعة. يرجى إحضار البطاقة الطبية (Medical Card) إن وجدت. نراكِ يوم الخميس. وداعاً.",
  "scenarios.gp.line10.speaker": "أنت",
  "scenarios.gp.line10.text": "شكراً لك. وداعاً.",
  "scenarios.gp.tip1": "قل 'I would like to make an appointment' (أود حجز موعد) — إنها عبارة مهذبة وواضحة.",
  "scenarios.gp.tip2": "اذكر اسمك بوضوح، وقم بتهجئته إذا لزم الأمر: 'F — A — T — I — M — A'.",
  "scenarios.gp.tip3": "قل 'Could you repeat that, please?' (هل يمكنك تكرار ذلك من فضلك؟) إذا لم تفهم شيئاً.",
  "scenarios.gp.tip4": "أحضر بطاقتك الطبية (إن وجدت) ورقم الـ PPS الخاص بك.",
  "scenarios.gp.tip5": "إذا كان الأمر عاجلاً جداً، قل: 'I need to see a doctor today — it is quite urgent.' (أحتاج لرؤية طبيب اليوم — الأمر عاجل للغاية).",

  "scenarios.school.title": "تسجيل طفل في المدرسة",
  "scenarios.school.description": "كيفية التواصل مع مدرسة في بورتلاويس للاستفسار عن تسجيل طفلك.",
  "scenarios.school.line1.speaker": "سكرتير المدرسة",
  "scenarios.school.line1.text": "مساء الخير، مدرسة سكويل موري الابتدائية. كيف يمكنني المساعدة؟",
  "scenarios.school.line2.speaker": "أنت",
  "scenarios.school.line2.text": "مرحباً. أنا أتصل بخصوص تسجيل ابنتي. تبلغ من العمر سبع سنوات.",
  "scenarios.school.line3.speaker": "سكرتير المدرسة",
  "scenarios.school.line3.text": "شكراً لاتصالك. بالفعل لدينا مقاعد شاغرة متوفرة. هل لي أن أسأل في أي صف ستلتحق؟ بالنسبة لطفلة عمرها سبع سنوات سيكون الصف الأول (First Class).",
  "scenarios.school.line4.speaker": "أنت",
  "scenarios.school.line4.text": "نعم، الصف الأول. لقد انتقلنا للتو إلى بورتلاويس من الخارج.",
  "scenarios.school.line5.speaker": "سكرتير المدرسة",
  "scenarios.school.line5.text": "مرحباً بكم في بورتلاويس! ستحتاج إلى ملء استمارة التسجيل. يمكنك استلامها من مكتب المدرسة أو يمكنني إرسالها إليك عبر البريد الإلكتروني.",
  "scenarios.school.line6.speaker": "أنت",
  "scenarios.school.line6.text": "هل يمكنك إرسالها عبر البريد الإلكتروني من فضلك؟ بريدي الإلكتروني هو fatima.hassan@email.com.",
  "scenarios.school.line7.speaker": "سكرتير المدرسة",
  "scenarios.school.line7.text": "ممتاز. ستحتاج أيضاً إلى نسخة من شهادة ميلادها ورقم الـ PPS الخاص بها. هل تمتلك هذه الأوراق؟",
  "scenarios.school.line8.speaker": "أنت",
  "scenarios.school.line8.text": "لدي شهادة ميلادها. وما زلت بانتظار صدور رقم الـ PPS.",
  "scenarios.school.line9.speaker": "سكرتير المدرسة",
  "scenarios.school.line9.text": "لا بأس بذلك — يمكنك إحضاره لاحقاً. بمجرد حصولنا على الاستمارة، سنتواصل معك لتحديد تاريخ البدء.",
  "scenarios.school.line10.speaker": "أنت",
  "scenarios.school.line10.text": "شكراً جزيلاً لك. هذا مفيد للغاية.",
  "scenarios.school.tip1": "الأوراق المطلوبة: شهادة الميلاد، رقم PPS (عند توفره)، وسجل التطعيمات الطبي.",
  "scenarios.school.tip2": "قل: 'We have just arrived from...' (لقد وصلنا للتو من...) — المدارس تتفهم ذلك وترحب بالجميع.",
  "scenarios.school.tip3": "اسأل: 'Does the school have English language support (EAL)?' (هل توفر المدرسة دعماً لتعليم اللغة الإنجليزية؟) — العديد من المدارس توفر ذلك.",
  "scenarios.school.tip4": "يوجد في بورتلاويس العديد من المدارس الابتدائية — يمكنك التقدم لأكثر من مدرسة في نفس الوقت.",
  "scenarios.school.tip5": "العام الدراسي يبدأ من شهر سبتمبر ويمتد حتى شهر يونيو.",

  "scenarios.council.title": "التواصل مع مجلس بلدية مقاطعة لويس",
  "scenarios.council.description": "الإبلاغ عن مشكلة صيانة في عقار تابع للمجلس البلدي (السقف والجدران).",
  "scenarios.council.line1.speaker": "موظف المجلس",
  "scenarios.council.line1.text": "صباح الخير، مجلس بلدية مقاطعة لويس. كيف يمكنني مساعدتك اليوم؟",
  "scenarios.council.line2.speaker": "أنت",
  "scenarios.council.line2.text": "مرحباً. أنا مستأجر لدى المجلس البلدي وأود الإبلاغ عن مشكلة في منزلي. هناك تسريب في السقف ورطوبة على الجدران.",
  "scenarios.council.line3.speaker": "موظف المجلس",
  "scenarios.council.line3.text": "يؤسفني سماع ذلك. بما أنه عقار تابع للمجلس، فنحن مسؤولون عن الإصلاحات الهيكلية. هل يمكنني الحصول على عنوانك من فضلك؟",
  "scenarios.council.line4.speaker": "أنت",
  "scenarios.council.line4.text": "نعم. 14 أوك درايف، بورتلاويس.",
  "scenarios.council.line5.speaker": "موظف المجلس",
  "scenarios.council.line5.text": "شكراً لك. سأقوم بتسجيل هذا الطلب لدى فريق صيانة الإسكان لدينا. سيتصل بك المفتش لمعاينة السقف والجدران.",
  "scenarios.council.line6.speaker": "أنت",
  "scenarios.council.line6.text": "شكراً لك. هل هناك أي شيء يجب أن أفعله في هذه الأثناء لمنع الرطوبة من التفاقم؟",
  "scenarios.council.line7.speaker": "موظف المجلس",
  "scenarios.council.line7.text": "يرجى الحفاظ على تهوية الغرف جيداً إذا أمكن ومسح أي رطوبة على الأسطح. سنحاول إرسال شخص إليك في أسرع وقت.",
  "scenarios.council.line8.speaker": "أنت",
  "scenarios.council.line8.text": "شكراً جزيلاً لك على مساعدتك. أنا في انتظار اتصال المفتش.",
  "scenarios.council.tip1": "رقم هاتف مجلس بلدية مقاطعة لويس: 4000 866 057.",
  "scenarios.council.tip2": "لإصلاحات الإسكان، قل: 'I am a council tenant and I want to report a maintenance issue' (أنا مستأجر لدى المجلس وأريد الإبلاغ عن مشكلة صيانة).",
  "scenarios.council.tip3": "المجلس البلدي مسؤول عن الهيكل الخارجي، بما في ذلك السقف، الجدران، والمصارف الرئيسية.",
  "scenarios.council.tip4": "يمكنك أيضاً زيارة مكاتب المجلس البلدي مباشرة في شارع جيمس فينتان لالور، بورتلاويس.",
  "scenarios.council.tip5": "قل: 'Could I speak to the housing maintenance department, please?' (هل يمكنني التحدث مع قسم صيانة الإسكان من فضلك؟).",

  "scenarios.pharmacy.title": "في الصيدلية",
  "scenarios.pharmacy.description": "صرف وصفة طبية أو طلب نصيحة حول دواء معين.",
  "scenarios.pharmacy.line1.speaker": "الصيدلاني",
  "scenarios.pharmacy.line1.text": "مرحباً، كيف يمكنني مساعدتك؟",
  "scenarios.pharmacy.line2.speaker": "أنت",
  "scenarios.pharmacy.line2.text": "مرحباً. لدي وصفة طبية من طبيبي. أود صرفها واستلام الدواء من فضلك.",
  "scenarios.pharmacy.line3.speaker": "الصيدلاني",
  "scenarios.pharmacy.line3.text": "بالتأكيد. هل يمكنني الحصول على اسمك وتاريخ ميلادك؟",
  "scenarios.pharmacy.line4.speaker": "أنت",
  "scenarios.pharmacy.line4.text": "اسمي أحمد الراوي. تاريخ ميلادي هو 12 يوليو 1985.",
  "scenarios.pharmacy.line5.speaker": "الصيدلاني",
  "scenarios.pharmacy.line5.text": "شكراً لك. هل لديك بطاقة طبية (Medical Card) أو بطاقة زيارة الطبيب العام؟",
  "scenarios.pharmacy.line6.speaker": "أنت",
  "scenarios.pharmacy.line6.text": "نعم، لدي بطاقة طبية.",
  "scenarios.pharmacy.line7.speaker": "الصيدلاني",
  "scenarios.pharmacy.line7.text": "ممتاز. هذه الوصفة الطبية تحتوي على مضادات حيوية. تناول حبة واحدة ثلاث مرات يومياً مع الطعام. تأكد من إنهاء العبوة كاملة حتى لو شعرت بالتحسن. هل لديك أي أسئلة؟",
  "scenarios.pharmacy.line8.speaker": "أنت",
  "scenarios.pharmacy.line8.text": "هل يمكنني تناول هذا الدواء مع أدوية أخرى؟",
  "scenarios.pharmacy.line9.speaker": "الصيدلاني",
  "scenarios.pharmacy.line9.text": "ما هي الأدوية الأخرى التي تتناولها حالياً؟",
  "scenarios.pharmacy.line10.speaker": "أنت",
  "scenarios.pharmacy.line10.text": "أنا آخذ حبوباً لضغط الدم — أملوديبين 5 ملغ (Amlodipine 5mg).",
  "scenarios.pharmacy.line11.speaker": "الصيدلاني",
  "scenarios.pharmacy.line11.text": "هذا جيد تماماً، لا يوجد أي تعارض طبي بينهما. ولكن تجنب المشروبات الكحولية تماماً أثناء فترة تناول المضاد الحيوي.",
  "scenarios.pharmacy.line12.speaker": "أنت",
  "scenarios.pharmacy.line12.text": "مفهوم. شكراً جزيلاً لك.",
  "scenarios.pharmacy.tip1": "أحضر معك دائماً الوصفة الطبية الأصلية، البطاقة الطبية، وهويتك الشخصية.",
  "scenarios.pharmacy.tip2": "قل: 'I do not understand — could you explain that more slowly, please?' (لم أفهم — هل يمكنك الشرح ببطء أكثر؟).",
  "scenarios.pharmacy.tip3": "اسأل: 'Are there any side effects I should know about?' (هل هناك أي أعراض جانبية يجب أن أعرفها؟).",
  "scenarios.pharmacy.tip4": "يقدم الصيادلة نصائح طبية مجانية — لا تحتاج دائماً للذهاب إلى الطبيب للمشاكل الصحية البسيطة.",
  "scenarios.pharmacy.tip5": "تقدم العديد من الصيدليات في بورتلاويس فحوصات مجانية لضغط الدم.",

  "scenarios.bus.title": "استخدام الحافلة / النقل العام",
  "scenarios.bus.description": "شراء تذكرة والاستفسار عن مسارات الحافلات في بورتلاويس.",
  "scenarios.bus.line1.speaker": "أنت",
  "scenarios.bus.line1.text": "معذرةً، هل تذهب هذه الحافلة إلى دبلن؟",
  "scenarios.bus.line2.speaker": "السائق",
  "scenarios.bus.line2.text": "نعم، هذه الحافلة متجهة مباشرة إلى محطة دبلن (Busáras). هل ستصعد معنا؟",
  "scenarios.bus.line3.speaker": "أنت",
  "scenarios.bus.line3.text": "نعم، من فضلك. كم تبلغ قيمة التذكرة الذهاب الواحدة إلى دبلن؟",
  "scenarios.bus.line4.speaker": "السائق",
  "scenarios.bus.line4.text": "تبلغ 13.50 يورو للذهاب فقط. هل لديك بطاقة ليب (Leap Card) الذكية؟",
  "scenarios.bus.line5.speaker": "أنت",
  "scenarios.bus.line5.text": "لا، ليس لدي بطاقة ليب. سأدفع نقداً.",
  "scenarios.bus.line6.speaker": "السائق",
  "scenarios.bus.line6.text": "لا مشكلة. 13.50 يورو من فضلك. يمكنني إرجاع الباقي لك.",
  "scenarios.bus.line7.speaker": "أنت",
  "scenarios.bus.line7.text": "تفضل هذه 20 يورو. شكراً لك. في أي وقت نصل إلى دبلن؟",
  "scenarios.bus.line8.speaker": "السائق",
  "scenarios.bus.line8.text": "يستغرق الطريق حوالي ساعة و15 دقيقة. سنصل في حدود الساعة 11:45.",
  "scenarios.bus.line9.speaker": "أنت",
  "scenarios.bus.line9.text": "شكراً لك. هل توجد دورة مياه داخل الحافلة؟",
  "scenarios.bus.line10.speaker": "السائق",
  "scenarios.bus.line10.text": "لا، لا توجد دورة مياه هنا. ولكن هناك توقف في منطقة موناستيريفين بعد حوالي 20 دقيقة إذا لزم الأمر.",
  "scenarios.bus.line11.speaker": "أنت",
  "scenarios.bus.line11.text": "شكراً جزيلاً لك.",
  "scenarios.bus.tip1": "بطاقة الـ Leap توفر الكثير من الأموال في الحافلات والقطارات. يمكنك شراؤها من محطة القطار أو المتاجر.",
  "scenarios.bus.tip2": "تنطلق حافلات (Bus Éireann) من بورتلاويس نحو دبلن وكورك والعديد من المدن الأخرى.",
  "scenarios.bus.tip3": "القطار (Irish Rail) هو خيار بديل رائع وسريع — وتتميز محطة قطار بورتلاويس بموقعها المركزي.",
  "scenarios.bus.tip4": "قل: 'Which bus stop do I need for...?' (أي موقف حافلة أحتاجه للوصول إلى...؟) إذا لم تكن متأكداً أين تنزل.",
  "scenarios.bus.tip5": "يمكنك التحقق من المواعيد بدقة عبر موقع buseireann.ie أو irishrail.ie.",
  
  "scenarios.welfare.title": "زيارة مكتب الرعاية الاجتماعية (Intreo)",
  "scenarios.welfare.description": "الاستفسار عن الإعانات المادية، وبدل الباحثين عن عمل، أو التسجيل للحصول على الدعم المهني.",
  "scenarios.welfare.line1.speaker": "موظف إنترو",
  "scenarios.welfare.line1.text": "صباح الخير. كيف يمكنني مساعدتك اليوم؟",
  "scenarios.welfare.line2.speaker": "أنت",
  "scenarios.welfare.line2.text": "صباح الخير. أنا أبحث عن معلومات بخصوص بدل الباحثين عن عمل (Jobseeker's Allowance). لقد فقدت وظيفتي مؤخراً.",
  "scenarios.welfare.line3.speaker": "موظف إنترو",
  "scenarios.welfare.line3.text": "يؤسفني سماع ذلك. كم من الوقت مضى على إقامتك في أيرلندا؟",
  "scenarios.welfare.line4.speaker": "أنت",
  "scenarios.welfare.line4.text": "أعيش هنا منذ عامين. ولدي تصريح إقامة رسمي.",
  "scenarios.welfare.line5.speaker": "موظف إنترو",
  "scenarios.welfare.line5.text": "جيد جداً. ستحتاج إلى إظهار بطاقة الـ PPSN الخاصة بك، وإثبات السكن الحالي، وتصريح الإقامة. هل قمت بالتسجيل معنا من قبل؟",
  "scenarios.welfare.line6.speaker": "أنت",
  "scenarios.welfare.line6.text": "لا، هذه هي المرة الأولى لي. لست متأكداً تماماً مما يجب علي فعله.",
  "scenarios.welfare.line7.speaker": "موظف إنترو",
  "scenarios.welfare.line7.text": "لا تقلق أبداً. سأعطيك استمارة لملئها. يمكننا مراجعتها وإكمالها معاً إذا أردت.",
  "scenarios.welfare.line8.speaker": "أنت",
  "scenarios.welfare.line8.text": "نعم من فضلك. لغتي الإنجليزية ليست مثالية تماماً وأريد التأكد من تعبئتها بشكل صحيح.",
  "scenarios.welfare.line9.speaker": "موظف إنترو",
  "scenarios.welfare.line9.text": "بالتأكيد — خذ وقتك بالكامل. إذا شعرت بالارتباك تجاه أي من الأسئلة، فقط توقف واطلب مني شرحها لك.",
  "scenarios.welfare.line10.speaker": "أنت",
  "scenarios.welfare.line10.text": "شكراً لك. إذا لم أفهم معنى أي كلمة، فسوف أسألك عنها. أقدر لك مساعدتك.",
  "scenarios.welfare.tip1": "يقع مكتب Intreo بورتلاويس في منطقة: (Portlaoise Employment Services, Togher Industrial Estate).",
  "scenarios.welfare.tip2": "الأوراق المطلوبة: بطاقة الـ PPSN، هوية بها صورة شخصية، إثبات سكن (مثل فاتورة كهرباء أو رسالة رسمية)، وتصريح الإقامة.",
  "scenarios.welfare.tip3": "لا تتردد في طرح الأسئلة أو طلب التوضيح إذا شعرت بالارتباك تجاه أي جزء من استمارات التقديم.",
  "scenarios.welfare.tip4": "قل عند وصولك: 'I would like to speak to a case officer, please.' (أود التحدث إلى مسؤول الحالة، من فضلك).",
  "scenarios.welfare.tip5": "يمكنك أيضاً التقديم على كافة الإعانات والطلبات إلكترونياً من خلال موقع mywelfare.ie الرسمي.",

  "camps.title": "مخيمات الصيف",
  "camps.subtitle": "اعثر على أفضل المخيمات للأطفال والشباب",
  "camps.filter.all": "كل الأنواع",
  "camps.filter.sport": "رياضة",
  "camps.filter.outdoor": "أنشطة خارجية",
  "camps.filter.creative": "إبداعي",
  "camps.location": "الموقع",
  "camps.map": "عرض الخريطة",
  "theme.light": "فاتح",
  "theme.dark": "داكن",
  "lang.switch": "English",
}

// Helper to build a minimal translation for a language with just nav + key UI
function minimal(nav: {
  home: string; laptop: string; learn: string; camps: string; cv: string
  learnBtn: string; healthTitle: string; healthText: string
  learnTitle: string; learnSubtitle: string; scenarios: string
  scenariosDesc: string; scenariosBrowse: string
  scenariosModalTitle: string; scenariosModalSubtitle: string
  scenariosBack: string; scenariosTips: string
  campsTitle: string; campsSubtitle: string
}): Record<string, string> {
  return {
    "nav.home": nav.home,
    "nav.laptop": nav.laptop,
    "nav.learn": nav.learn,
    "nav.camps": nav.camps,
    "nav.cv": nav.cv,
    "home.learn.btn": nav.learnBtn,
    "home.health.title": nav.healthTitle,
    "home.health.text": nav.healthText,
    "learn.title": nav.learnTitle,
    "learn.subtitle": nav.learnSubtitle,
    "learn.scenarios": nav.scenarios,
    "learn.scenarios.desc": nav.scenariosDesc,
    "learn.scenarios.browse": nav.scenariosBrowse,
    "scenarios.title": nav.scenariosModalTitle,
    "scenarios.subtitle": nav.scenariosModalSubtitle,
    "scenarios.back": nav.scenariosBack,
    "scenarios.tips": nav.scenariosTips,
    "camps.title": nav.campsTitle,
    "camps.subtitle": nav.campsSubtitle,
  }
}

// Non-core languages removed — only en, ar, ku, ps, fa are supported.

// Kurdish (Kurmanji)
const ku = minimal({
  home: "Mal", laptop: "Rêbera Laptopê", learn: "Îngilîzî Fêr Bibe",
  camps: "Kampên Havînê", cv: "CV Çêke", learnBtn: "Dest Pê Bike",
  healthTitle: "Tenduristî", healthText: "Bijîşkek bixwaze. Di rewşên acil de 112 an 999 bang bike.",
  learnTitle: "Çavkaniyên Fêrbûna Îngilîzî", learnSubtitle: "Çavkaniyên înternetê ji bo fêrbûna Îngilîzî li malê",
  scenarios: "Senaryoyên Gotûbêjê", scenariosDesc: "Gotûbêjên rastîn ji bo jiyana rojane li Portlaoise.",
  scenariosBrowse: "Senaryoyên Gotûbêjê Bibîne", scenariosModalTitle: "Senaryoyên Gotûbêjê",
  scenariosModalSubtitle: "Gotûbêjên rastîn ji bo rewşên rojane li Portlaoise, Îrlanda.",
  scenariosBack: "Vegerê", scenariosTips: "Şîretên bikêr ji bo vê rewşê",
  campsTitle: "Kampên Havînê", campsSubtitle: "Çêtirîn kampên ji bo zarok û ciwanan bibîne",
})

// Pashto (Afghan)
const ps = minimal({
  home: "کور", laptop: "د لیپ ټاپ لارښود", learn: "انګلیسي زده کړئ",
  camps: "د دوبي کیمپونه", cv: "د CV جوړول", learnBtn: "زده کړه پیل کړئ",
  healthTitle: "روغتیا پاملرنه", healthText: "ډاکتر وګورئ. بیړني حالت کې ۱۱۲ یا ۹۹۹ ته زنګ ووهئ.",
  learnTitle: "د انګلیسي زده کړې سرچینې", learnSubtitle: "د انګلیسي د کور نه زده کولو لپاره آنلاین سرچینې",
  scenarios: "د خبرو سیناریوګانې", scenariosDesc: "د پورتلاویس ورځني ژوند لپاره ریښتیني خبرې وکړئ.",
  scenariosBrowse: "د خبرو سیناریوګانې وګورئ", scenariosModalTitle: "د خبرو سیناریوګانې",
  scenariosModalSubtitle: "د پورتلاویس، آیرلنډ ورځنیو حالاتو کې د باور لپاره ریښتیني خبرې.",
  scenariosBack: "بیرته", scenariosTips: "د دې حالت لپاره ګټورې لارښوونې",
  campsTitle: "د دوبي کیمپونه", campsSubtitle: "د ماشومانو او ځوانانو لپاره غوره کیمپونه ومومئ",
})

// Dari / Persian (also spoken widely in Afghanistan)
const fa = minimal({
  home: "خانه", laptop: "راهنمای لپ‌تاپ", learn: "یادگیری انگلیسی",
  camps: "کمپ‌های تابستانی", cv: "ساخت رزومه", learnBtn: "شروع یادگیری",
  healthTitle: "مراقبت‌های بهداشتی", healthText: "به پزشک مراجعه کنید. در موارد اضطراری با ۱۱۲ یا ۹۹۹ تماس بگیرید.",
  learnTitle: "منابع یادگیری انگلیسی", learnSubtitle: "منابع آنلاین برای یادگیری انگلیسی در خانه",
  scenarios: "سناریوهای مکالمه", scenariosDesc: "مکالمات واقعی برای زندگی روزمره در پورتلاویش.",
  scenariosBrowse: "مرور سناریوهای مکالمه", scenariosModalTitle: "سناریوهای مکالمه",
  scenariosModalSubtitle: "مکالمات واقعی برای اعتماد در موقعیت‌های روزمره در پورتلاویش، ایرلند.",
  scenariosBack: "بازگشت", scenariosTips: "نکات مفید برای این موقعیت",
  campsTitle: "کمپ‌های تابستانی", campsSubtitle: "بهترین کمپ‌ها برای کودکان و جوانان را پیدا کنید",
})

// Initialize i18next once (client-side singleton)
if (!i18n.isInitialized) {
  i18n
    .use(LanguageDetector)
    .use(initReactI18next)
    .init({
      resources: {
        en: { translation: en },
        ar: { translation: ar },
        ku: { translation: ku },
        ps: { translation: ps },
        fa: { translation: fa },
      },
      fallbackLng: "en",
      interpolation: { escapeValue: false },
      detection: { order: ["localStorage", "navigator"], caches: ["localStorage"] },
    })
}

// ─── RTL language codes ───────────────────────────────────────────────────────
const RTL_LANGS = new Set(["ar", "fa", "ur", "he", "yi", "ps", "ku"])

// ─── Context ──────────────────────────────────────────────────────────────────
interface LanguageContextType {
  language: string
  setLanguage: (lang: string) => void
  t: (key: string) => string
  isRTL: boolean
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function LanguageProvider({ children }: { children: ReactNode }) {
  const { t: i18nT, i18n: i18nInstance } = useTranslation()
  const [language, setLanguageState] = useState<string>(i18nInstance.language || "en")

  const setLanguage = (lang: string) => {
    i18nInstance.changeLanguage(lang)
    setLanguageState(lang)
  }

  useEffect(() => {
    const handler = (lng: string) => setLanguageState(lng)
    i18nInstance.on("languageChanged", handler)
    return () => i18nInstance.off("languageChanged", handler)
  }, [i18nInstance])

  const t = (key: string): string => i18nT(key)
  const isRTL = RTL_LANGS.has(language.split("-")[0])

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, isRTL }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) throw new Error("useLanguage must be used within a LanguageProvider")
  return context
}
